services:  
  reservasdb:
      image: mongo
      container_name: reservasdb
      restart: always
      ports:
        - 27017:27017
      volumes:
        - mongodb_data:/data/db
      environment:
        - MONGO_INITDB_DATABASE=restaurant-reservations
      networks:
        - app-network

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: reservas-app
    restart: always
    depends_on:
      - reservasdb
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
